#!/usr/bin/env bash

#Creates derivative project importing ubiquitous_bash as a static library.

workingDir="$PWD"

devName=newDeveloperName
projectName=newProjectName

#All content in this folder not owned by other authors is intended to be public domain. Other copyright notices may be provided as templates. See license.txt for details.

mkdir "$projectName"
cd ./"$projectName"

mkdir ./_lib
mkdir ./_prog

git init

git submodule add --depth 1 git@github.com:mirage335/ubiquitous_bash.git ./_lib/ubiquitous_bash

#Parent derivative of ubiquitous_bash.
#cd ./_lib/parent
#git submodule update --depth 1 --init ./_lib/ubiquitous_bash
#cd "$workingDir"/"$projectName"

#git submodule update --depth 1 --init --recursive

cp ./_lib/ubiquitous_bash/ubiquitous_bash.sh ./
cp ./_lib/ubiquitous_bash/compile.sh ./
cp ./_lib/ubiquitous_bash/license.txt.gpl ./license.txt
cp ./_lib/ubiquitous_bash/README.md.template ./README.md

find . -maxdepth 1 -type f -exec sed -i s/Project/"$projectName"/g {} \;
find . -maxdepth 1 -type f -exec sed -i s/DeveloperName/"$devName"/g {} \;
find . -maxdepth 1 -type f -exec sed -i s/YEAR/$(date +%Y)/g {} \;

##### Binary Executables
mkdir -p ./_bin
cp -a ./_lib/ubiquitous_bash/_bin/. ./_bin
mkdir -p ./_lib
#cp -a ./_lib/ubiquitous_bash/_lib/. ./_lib
mkdir -p ./_bundle
cp -a ./_lib/ubiquitous_bash/_bundle/. ./_bundle

##### Hardcoded Configuration
mkdir -p ./_config
cp -a ./_lib/ubiquitous_bash/_config/. ./_config

##### Commonly customized scripts.

#cp ./_lib/ubiquitous_bash/generic/process/daemon.sh

#cp ./_lib/ubiquitous_bash/structure/localfs.sh ./_prog/

#cp ./_lib/ubiquitous_bash/structure/localenv.sh ./_prog/

#cp ./_lib/ubiquitous_bash/structure/installation.sh ./_prog/

##### Parent Derivative Scripts
#mkdir -p ./_prog
#cp -a ./_lib/parent/_prog/. ./_prog

##### Dedicated program scripts.

echo -n >> ./_prog/specglobalvars.sh

echo '##### Core' >> ./_prog/core.sh
echo '' >> ./_prog/core.sh

cp ./_lib/ubiquitous_bash/structure/program.sh ./_prog/

cp ./_lib/ubiquitous_bash/build/bash/compile_bash_prog.sh ./_prog/
cp ./_lib/ubiquitous_bash/build/bash/generate_bash_prog.sh ./_prog/

##### Runtime Configuration

#mkdir -p ./_local/ssh
#cp -d --preserve=all ./_lib/ubiquitous_bash/_lib/ssh/ops ./_local/ssh/ops

#Parent derivative of ubiquitous_bash.
#cp -d --preserve=all ./_lib/parent/_lib/ubiquitous_bash/_lib/ssh/ops ./_local/ssh/ops

#cp -a ./_lib/coreautossh/_local ./


./compile.sh

git add -A .
git commit -a -m "first commit"





