extends: airbnb-base
parser: babel-eslint
env:
  browser: true
  node: true
  jasmine: true

globals:
  atom: true

settings:
  import/core-modules: [ atom ]

rules:
  no-restricted-syntax: [0, "FunctionExpression", "no-restricted-syntax"]
  no-param-reassign: [0]
  class-methods-use-this: [0]
  default-case: [0]
  guard-for-in: [0]
  no-this-before-super: [0]
  prefer-rest-params: [0]
