
# Intended to designate a build (eg. of 'ubcp') as suitable for internal integration with a larger project (eg. 'ubdist') .
# Before designating a new build internal, consider renaming an existing internal designated build to 'internal-YYYY-MM-DD' by the 'renameTag-build_to_internal' Github Actions workflow.
# If compatible or successful as documented (eg. specific features tested) or expected (ie. all essential features tested), the next step would be to tag as 'certified' with a date.


# ATTRIBUTION-AI - Largely attributable to ChatGPT GPT-4 2023-06-26 .
# 'Please provide code to run the git tag and git push commands in a Github Actions YML script using the privileges of secrets.GITHUB_TOKEN .'
# 'Will git automatically use the 'GITHUB_TOKEN' environment variable by default? Is this actually built into mainline versions of the git software?'
# 'Please provide a github actions YML script to copy a git release name to another name.'
# 'Google search seems to indicate 'gh' is already preinstalled with all github runners.'
# ...


name: _renameTag-build_to_internal


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: write
  checks: read
  contents: write
  deployments: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: read


  
on:
  workflow_dispatch:
    #inputs:
      #source_tag:
        #description: 'Source Tag'
        #required: true
      #target_tag:
        #description: 'Target Tag'
        #required: true
        

jobs:
  copy-release:
    runs-on: ubuntu-latest
    steps:



      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # we need fetch-depth: 0 to fetch all tags

      - name: Update release
        run: |
          _safeEcho ()
          {
              printf '%s' "$1";
              shift;
              [[ "$@" == "" ]] && return 0;
              local currentArg;
              for currentArg in "$@";
              do
                  printf '%s' " ";
                  printf '%s' "$currentArg";
              done;
              return 0
          }
          
          
          # Fetch all releases
          releases=$(gh api repos/mirage335/ubiquitous_bash/releases)


          # Find the tag name for the release by its name
          tag_name=$(echo "$releases" | jq -r '.[] | select(.name == "internal") | .tag_name' | cat)
          
          # Edit the release using its tag name
          if [[ "$tag_name" != "" ]]
          then
            gh release delete "$tag_name" --confirm
          fi


          # Find the tag name for the release by its name
          tag_name=$(echo "$releases" | jq -r '.[] | select(.name == "internal"-$(date +'%Y-%m-%d')) | .tag_name' | cat)
          
          # Edit the release using its tag name
          if [[ "$tag_name" != "" ]]
          then
            gh release delete "$tag_name" --confirm
          fi

          
          # Find the tag name for the release by its name
          tag_name=$(echo "$releases" | jq -r '.[] | select(.name == "build") | .tag_name')
          body=$(echo "$releases" | jq -r '.[] | select(.name == "your_release_name") | .body' | tr -dc 'a-zA-Z0-9.:\=\_\-/%+\ \n')
          
          # Edit the release using its tag name
          _safeEcho "$body" | gh release edit "$tag_name" --title "internal" --notes -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


