
# Intended to designate a build (eg. of 'ubcp') as suitable for internal integration with a larger project (eg. 'ubdist') .
# Before designating a new build internal, consider renaming an existing internal designated build to 'internal-YYYY-MM-DD' by the 'renameTag-build_to_internal' Github Actions workflow.
# If compatible or successful as documented (eg. specific features tested) or expected (ie. all essential features tested), the next step would be to tag as 'certified' with a date.


# ATTRIBUTION-AI - Largely attributable to ChatGPT GPT-4 2023-06-26 .
# 'Please provide code to run the git tag and git push commands in a Github Actions YML script using the privileges of secrets.GITHUB_TOKEN .'
# 'Will git automatically use the 'GITHUB_TOKEN' environment variable by default? Is this actually built into mainline versions of the git software?'
# 'Please provide a github actions YML script to copy a git release name to another name.'
# 'Google search seems to indicate 'gh' is already preinstalled with all github runners.'
# ...


name: _renameTag-build_to_internal


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: write
  checks: read
  contents: write
  deployments: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: read


  
on:
  workflow_dispatch:
    #inputs:
      #source_tag:
        #description: 'Source Tag'
        #required: true
      #target_tag:
        #description: 'Target Tag'
        #required: true
        

jobs:
  copy-release:
    runs-on: ubuntu-latest
    steps:
      
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        continue-on-error: true
        with:
            tag_name: internal #(required) tag name to delete 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            delete_release: true #(optional) default: true 

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      #- uses: dev-drprasad/delete-tag-and-release@v1.0
        #with:
            #tag_name: internal-${{ steps.date.outputs.date }} #(required) tag name to delete 
            #github_token: ${{ secrets.GITHUB_TOKEN }}
            #delete_release: true #(optional) default: true 



      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # we need fetch-depth: 0 to fetch all tags

      #- name: Set up GitHub CLI
        #run: gh auth login --with-token <<< "${{ secrets.TOKEN_UB }}"

      - name: Fetch release data
        id: fetch_release_data
        run: |
          RELEASE_DATA=$(gh release view build --json body -q '.body')
          echo "::set-output name=release_body::$(echo "$RELEASE_DATA")"

          RELEASE_ID=$(gh api repos/${{ github.repository }}/releases/tags/build -q .id)
          echo "::set-output name=release_id::$(echo "$RELEASE_ID")"

      - name: Update release
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -f internal build
          git tag -d build
          git push https://${{ secrets.TOKEN_UB }}@github.com/mirage335/ubiquitous_bash.git internal
          git push --delete https://${{ secrets.TOKEN_UB }}@github.com/mirage335/ubiquitous_bash.git build
          gh release edit build --title "internal" --notes "${{ steps.fetch_release_data.outputs.release_body }}"
          gh api repos/${{ github.repository }}/releases/${{ steps.fetch_release_data.outputs.release_id }} -X PATCH -F tag_name=internal


