
# WARNING: May be untested .

name: build
on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    #- cron: '5 1 * * 6'
    #- cron: '5 1 * * 2,4'
    #- cron: '5 1 * * 2'
    - cron: '5 1 * * 4'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://svrooij.io/2021/08/17/github-actions-secret-file/
jobs:
  build_ubcp:
    runs-on: windows-latest # Code should run on any platform, change accordingly
    steps:
      - uses: actions/checkout@v2
      # https://svrooij.io/2021/08/17/github-actions-secret-file/
      #$secretFileHash = Get-FileHash $secretFile;
      #Write-Output "::set-output name=SECRET_FILE::$secretFile";
      #Write-Output "::set-output name=SECRET_FILE_HASH::$($secretFileHash.Hash)";
      #Write-Output "Secret file $secretFile has hash $($secretFileHash.Hash)";
      #Get-Content -Path $secretFile | Measure-Object -Line -Word -Character;
      #echo $secretFile;
      #echo $($secretFileHash.Hash)
      - name: write! secrets
        id: secret-file1
        run: |
          $secretFile = "/rclone.conf";
          $encodedBytes = [System.Convert]::FromBase64String($env:rclone_limited_conf_base64);
          Set-Content $secretFile -Value $encodedBytes -AsByteStream
        shell: pwsh
        env:
          rclone_limited_conf_base64: ${{ secrets.rclone_limited_conf_base64 }}
      - name: statement! ls
        run: |
          ls;
          ls /
        shell: pwsh
      - name: build_ubcp_powershell
        run: |
          ./_lib/kit/install/cloud/zSpecial/msw/build_ubcp/build_ubcp_powershell.ps1
        shell: pwsh
      - name: statement! ls
        run: |
          ls;
          ls /
        shell: pwsh
      - name: statement! ubcp-cygwin-portable-installer
        run: |
          cat /ubcp-cygwin-portable-installer.log
        shell: pwsh
      - name: statement! _setupUbiquitous
        run: |
          cat /_setupUbiquitous.log
        shell: pwsh
      - name: statement! statistics! _mitigate-ubcp
        run: |
          Get-Content -Path /_mitigate-ubcp.log | Measure-Object -Line -Word -Character
        shell: pwsh
      - name: statement! package_ubiquitous_bash-msw
        run: |
          cat /package_ubiquitous_bash-msw.log
        shell: pwsh
      - name: statement! test-lean
        run: |
          cat /_test-lean.log
        shell: pwsh







