


name: zExperiment


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none



on:
  workflow_dispatch:
        

jobs:
  zExperiment:
    runs-on: ubuntu-latest
    steps:
      - name: _getCore_ub
        shell: bash
        timeout-minutes: 90
        run: |
          mkdir -p ~/core/infrastructure
          cd ~/core/infrastructure
          git clone --depth 1 --recursive https://github.com/mirage335/ubiquitous_bash.git
          cd ubiquitous_bash
          ./_setupUbiquitous.bat
      - name: _getMinimal_cloud
        shell: bash
        run: |
          ~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _getMinimal_cloud
        timeout-minutes: 90
      #- name: _vnchost-setup
        #shell: bash
        #run: |
          #~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _vnchost-setup
        #timeout-minutes: 90
      #- name: write! secrets
        #shell: bash
        #run: |
          #~/core/infrastructure/ubiquitous_bash/ubiquitous_bash.sh _prepare_rclone_limited_file
        #env:
          #rclone_limited_conf_base64: ${{ secrets.rclone_limited_conf_base64 }}
        #timeout-minutes: 5
      - uses: actions/checkout@v2
#      # DANGER: Discouraged !
#      - name: Setup upterm session
#        #if: ${{ failure() }}
#        uses: lhotari/action-upterm@v1
#        with:
#          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
#          limit-access-to-actor: true
#          ## limits ssh access and adds the ssh public keys of the listed GitHub users
#          # DANGER: Discouraged. Prefer 'limit-access-to-actor' instead.
#          #limit-access-to-users: githubuser1,githubuser2
#        timeout-minutes: 320
#        # DANGER: Discouraged !
#        #env:
#          #GH_TOKEN: ${{ github.token }}













